### ISSUE TITLE
Ambassador 0.5.0-RC4 attempts to list all secrets in cluster even with AMBASSADOR_SINGLE_NAMESPACE

### ISSUE THREAD

**Issue by davidharkis** [datawire/ambassador#1098]
**Describe the bug**
Ambassador 0.5.0-RC4 attempts to list all secrets in cluster even with AMBASSADOR_SINGLE_NAMESPACE set to true.

**To Reproduce**
1. Run Ambassador with below conditions
AMBASSADOR_SINGLE_NAMESPACE 'true' & AMBASSADOR_NAMESPACE set
Service Account that only has access to secrets within the chosen namespace/project
2. Observe log
[ambassador-test-31-5fm8q.log](https://github.com/datawire/ambassador/files/2746746/ambassador-test-31-5fm8q.log)

**Expected behavior**
Ambassador will only attempt to list secrets within the chosen namespace/project

**Versions:**
 - Ambassador: 0.5.0-RC4 
 - Kubernetes environment : Openshift
 - Version: 3.6

**Additional context**
Does not occur in RC3

**Comment by cornelius-keller** [comment]
We can confirm that 0.5.0-RC4 tries to read secrets at cluster scope even if it is configured to be restricted to a single namespace.

**Comment by jsrolon** [comment]
Just to report, this issue seems to still be present in 0.50.0-rc5.

**Comment by richarddli** [comment]
Correct, this is mentioned in the release notes: https://blog.getambassador.io/ambassador-0-50-rc5-available-9901d01c7a46

**Comment by jmays4** [comment]
To add to this issue, it is not only secrets that do not honor single namespace, but the AuthService and route tables are also crossing namespaces when AMBASSADOR_SINGLE_NAMESPACE  is set

**Comment by christianhuening** [comment]
Yeah just ran into this as well! Have 2 namespaces which feature the same naming scheme but different ambassador instances. got a flappy service routing by ambassador in the 2nd namespace as it was shadowed by the instance in the first one.

**Comment by kflynn** [comment]
Fixed in RC6.

**Comment by davidharkis** [comment]
I'm still seeing this in RC6 too.

[ambassador-test-39-t524h.log](https://github.com/datawire/ambassador/files/2811745/ambassador-test-39-t524h.log)

**Comment by kflynn** [comment]
Reopening with our apologies – I carefully tested to make sure Ambassador didn't see things outside the namespace, but I just realized that I left RBAC too permissive to catch this. Mea culpa!

**Comment by kflynn** [comment]
Fixed in #1170.
