### ISSUE TITLE
Registration of new routes very slow

### ISSUE THREAD

**Issue by JorritPosthuma** [datawire/ambassador#1148]
**Describe the bug**
We have a platform where we dynamically add new routes. In version 0.40.2 is takes around 2 second for a simple container to be accessible through the route, but in 0.50.0-rc5, it takes around 20 seconds

**To Reproduce**
The route we apply is as follows:
```
apiVersion: ambassador/v1
kind:  Mapping
name:  module_x_mapping
prefix: /module_x/
service: module_x
timeout_ms: 0
```
We create the service with this config using the Kubernetes TypeScript SDK.

**Expected behavior**

**Versions (please complete the following information):**
 - Ambassador: 0.50.0-rc5
 - Kubernetes environment: Docker for Mac 2.0.0.2 - Kubernetes: v1.10.11

**Additional context**
Looking at the Ambassador Diagnostic Overview, the route get's picked up very quickly. But then it still needs 20 seconds to become reachable.

**Comment by kflynn** [comment]
This should be fixed by #1153.

**Comment by kflynn** [comment]
Fixed in RC6.

**Comment by kflynn** [comment]
In 0.50.0 GA? How many services do you have?

**Comment by JorritPosthuma** [comment]
Ah, ok, no, I tried RC6 :). Will try GA first! If that doesn't resolve anything then I'll contact on slack.

PS: Around 10 services

**Comment by kflynn** [comment]
Ahhhhh that makes much more sense. RC6 definitely had an issue there, but 0.50.0 GA should be much better for you. 😄
