### ISSUE TITLE
statsd-sink "Name does not resolve"

### ISSUE THREAD

**Issue by kellycampbell** [datawire/ambassador#465]
**Describe the bug**
Ambassador was not responding timely to requests. 
Symptoms seem similar to #446 

ambassador was logging this msg about 200 times per second from the `statsd` container of a single pod:

```
socat[7776] E getaddrinfo("statsd-sink", "NULL", {1,0,2,17}, {}): Name does not resolve
```

This started immediately after scaling the ambassador deployment from 1 to 2 pods.

**Versions (please complete the following information):**
 - Ambassador: 0.33.1
 - Kubernetes environment: AWS using kops
 - Version: 1.7.12, kernel 4.4.111-k8s
 - Calico version: quay.io/calico/node:v2.6.2, quay.io/calico/cni:v1.11.0

**Additional Info:**

ambassador deployment config:
```
      containers:
      - name: ambassador
        image: quay.io/datawire/ambassador:0.33.1
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: AMBASSADOR_SINGLE_NAMESPACE
          value: "true"
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AMBASSADOR_RESTART_TIME
          value: "20"
        - name: AMBASSADOR_DRAIN_TIME
          value: "10"
        - name: AMBASSADOR_SHUTDOWN_TIME
          value: "15"
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
      - name: statsd
        image: quay.io/datawire/statsd:0.33.1
```

**Comment by richarddli** [comment]
Thanks for the bug report. This occurs when you don't have `statsd` configured. The errors should be harmless, but you can also delete the `statsd` container from the standard deployment. I'll leave this open, as we should update the documentation to explain that this container should be removed if you're not doing monitoring.

**Comment by kellycampbell** [comment]
Ok, thanks. The same deployment had a pod running fine for a couple days.
It was only the new pod after I scaled that had the problem.

**Comment by richarddli** [comment]
I pushed a docs update to here: https://www.getambassador.io/reference/running in the Default Configuration notes. There's probably a better way for us to handle this, but I'm going to close this for now.

**Comment by manigandham** [comment]
We just ran into this too. IMO this issue needs to be reopened as this issue still occurs and isn't resolved, especially since the only advice seems to be to turn the feature off...?

**Comment by manigandham** [comment]
Alright, upon further review looks like this is the statsd container itself logging errors repeatedly because it can't reach the `statsd-sink` service, which isn't included by default in the Ambassador install.

There's a [recent commit to disable the Socat logging](https://github.com/datawire/ambassador/commit/0ea51cc1c09fb33e65921f9d931908b70879d684) but it doesn't seem to have an effect on this particular message for  `socat[28980] E getaddrinfo("statsd-sink", "NULL", {1,0,2,17}, {}): Name does not resolve`

It would help to make this situation explicit in the documentation, or to remove the statsd container and have that be optional to add in later rather than opt-out, especially since the errors and logging do take up a considerable amount of resources on the cluster.

**Comment by containscafeine** [comment]
@manigandham this is tracked in #568
