### ISSUE TITLE
Users would like an easy way to get a cert from LetsEncrypt

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#49]
We can probably fire up certbot easily...

**Comment by kminehart** [comment]
#191 

:)

**Comment by bhack** [comment]
https://github.com/datawire/ambassador/pull/191#issuecomment-394155263

**Comment by bhack** [comment]
Is it solved with https://github.com/datawire/ambassador/pull/505?

**Comment by richarddli** [comment]
Yes. Thanks for reminding me to close the issue. :)

**Comment by samuela** [comment]
It's still not entirely clear how to set this whole thing up. Is there any way that we could get a full tutorial on setting up cert-manager and getting it to talk to ambassador?
